// windows.h first: shlobj.h and shellapi.h assume its types.
#include <windows.h>
#include <shlobj.h>   // SHCreateItemFromParsingName, SHParseDisplayName, IEnumShellItems
#include <shellapi.h> // ShellExecuteExW, ShellExecuteW

#include "appsapi.h"

#include <QBuffer>
#include <QByteArray>
#include <QDateTime>
#include <QDebug>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QImage>
#include <QJsonDocument>
#include <QJsonObject>
#include <QStandardPaths>
#include <QStringView>
#include <QVariantMap>

#include <algorithm>
#include <cmath>
#include <string>

namespace {

constexpr int kIconPixels = 32;
constexpr int kIconMaxPixels = 48;   // BIGGERSIZEOK can hand back 96 or 256
constexpr int kIconCacheCap = 512;   // ~2 KB each; a full list still fits
constexpr int kUsageCap = 200;       // launch history kept, most recent first

// Enumerating AppsFolder measures ~300 ms warm and ~600 ms cold, and that is
// the shell's own cost - asking for no display names at all is just as slow.
// It must therefore never land on a summon, so the window is far longer than
// any burst of launcher use; installing an app is the rare event, and the
// plugin triggers a scan shortly after startup anyway.
constexpr int kRescanWindowMs = 5 * 60 * 1000;

// AppsFolder hands out a bare app id, which on its own parses back to
// nothing (0x80070002). This is the prefix that makes it an absolute name
// SHParseDisplayName and SHCreateItemFromParsingName both accept.
const QString kAppsFolderPrefix = QStringLiteral("shell:AppsFolder\\");

// Start-menu shortcuts with no registered AppUserModelID get a synthesised
// one. It is a GUID with a fixed prefix: nothing to show the user, and
// matching against it would only invent hits on its hex digits.
bool isSynthesisedAppId(const QString &appId)
{
    return appId.startsWith(QStringLiteral("Microsoft.AutoGenerated."));
}

// "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App" -> "Microsoft.WindowsCalculator".
// Both what is shown and what is matched against: the family hash is random
// letters, and the "!App" entry point is shared by nearly every packaged app,
// so keeping either only manufactures matches.
QString prettyAppId(const QString &appId)
{
    if (isSynthesisedAppId(appId))
        return {};
    if (!appId.contains(QLatin1Char('!')))
        return appId; // a Win32 entry: usually just "chrome.exe"
    const qsizetype underscore = appId.indexOf(QLatin1Char('_'));
    return underscore > 0 ? appId.left(underscore) : appId;
}

// The shell hands out a 32-bit top-down DIB. Converted by hand rather than
// through QImage::fromHBITMAP because the alpha channel is the whole point
// here - an icon that loses it renders as a black tile - and this spells the
// format out instead of depending on what the helper picks.
QImage imageFromHBitmap(HBITMAP bitmap)
{
    BITMAP header = {};
    if (!GetObjectW(bitmap, sizeof(header), &header)
        || header.bmWidth <= 0 || header.bmHeight <= 0) {
        return {};
    }

    QImage image(header.bmWidth, header.bmHeight, QImage::Format_ARGB32_Premultiplied);
    if (image.isNull())
        return {};

    BITMAPINFO info = {};
    info.bmiHeader.biSize = sizeof(BITMAPINFOHEADER);
    info.bmiHeader.biWidth = header.bmWidth;
    info.bmiHeader.biHeight = -header.bmHeight; // negative: top-down, as QImage stores it
    info.bmiHeader.biPlanes = 1;
    info.bmiHeader.biBitCount = 32;
    info.bmiHeader.biCompression = BI_RGB;

    const HDC dc = GetDC(nullptr);
    const int rows = GetDIBits(dc, bitmap, 0, UINT(header.bmHeight),
                               image.bits(), &info, DIB_RGB_COLORS);
    ReleaseDC(nullptr, dc);
    if (rows == 0)
        return {};

    // A few icon sources come back 32bpp with the alpha byte left at zero,
    // which is indistinguishable from fully transparent. Nothing is lost by
    // forcing those opaque: a genuinely invisible icon is not a case worth
    // preserving.
    const int pixels = image.width() * image.height();
    auto *bits = reinterpret_cast<quint32 *>(image.bits());
    bool anyAlpha = false;
    for (int i = 0; i < pixels; ++i) {
        if ((bits[i] & 0xFF000000u) != 0) {
            anyAlpha = true;
            break;
        }
    }
    if (!anyAlpha) {
        for (int i = 0; i < pixels; ++i)
            bits[i] |= 0xFF000000u;
    }
    return image;
}

// "Visual Studio Code" -> "vsc". Its own matching tier, so "vsc" finds it
// without that run of letters appearing in the name anywhere.
QString initialsOf(const QString &name)
{
    QString out;
    bool atWordStart = true;
    for (const QChar c : name) {
        if (!c.isLetterOrNumber()) {
            atWordStart = true;
            continue;
        }
        if (atWordStart)
            out.append(c.toLower());
        atWordStart = false;
    }
    return out;
}

// fzf-lite, anchored: the query's first character has to land on a word
// start, and the rest must then appear in order. Adjacent hits are free, each
// gap costs, so "vsc" scores better against "Visual Studio Code" than against
// "Verbose Syslog Console". Returns a penalty, or -1 for no match.
//
// The anchor is what stops this last-resort tier from being a junk drawer.
// Unanchored, "pppp" is a subsequence of "Sample Desktop Apps" - and of most
// long names - so a query of pure noise still filled the list with confident
// looking matches.
int subsequencePenalty(const QString &hay, const QString &needle)
{
    if (hay.isEmpty() || needle.isEmpty())
        return -1;

    qsizetype start = -1;
    for (qsizetype i = 0; i < hay.size(); ++i) {
        if (hay.at(i) == needle.at(0) && (i == 0 || !hay.at(i - 1).isLetterOrNumber())) {
            start = i;
            break;
        }
    }
    if (start < 0)
        return -1;

    qsizetype at = start;
    qsizetype previous = -2;
    int penalty = int(std::min<qsizetype>(40, start)); // a later anchor matches less well
    for (const QChar c : needle) {
        while (at < hay.size() && hay.at(at) != c)
            ++at;
        if (at >= hay.size())
            return -1;
        if (at != previous + 1) {                     // a gap, not a run
            // Steep on purpose: letters scattered across a long name are a
            // near-worthless signal, and a gentler curve let "notep" pull
            // "Windows Software Development Kit" over Notepad itself.
            const qsizetype gap = previous < 0 ? 0 : at - previous - 1;
            penalty += 6 + 2 * int(gap);
        }
        previous = at;
        ++at;
    }
    return penalty;
}

// Tiers, best first, all on already-lowercased text. The gaps between them
// are wide enough that a better kind of match wins on the name alone;
// frecency is added afterwards and can only re-rank within about two tiers.
int matchScore(const QString &query, const QString &lowerName, const QString &initials,
               const QString &lowerAppId)
{
    if (lowerName == query)
        return 1000;
    if (lowerName.startsWith(query))
        return 900 - int(std::min<qsizetype>(80, lowerName.size() - query.size()));
    if (!initials.isEmpty()) {
        if (initials == query)
            return 880;
        if (initials.startsWith(query))
            return 820;
    }
    // A later word starting with the query: "code" finding "Visual Studio Code".
    for (qsizetype i = 1; i < lowerName.size(); ++i) {
        if (!lowerName.at(i - 1).isLetterOrNumber() && lowerName.at(i).isLetterOrNumber()
            && QStringView(lowerName).sliced(i).startsWith(query)) {
            return 760 - int(std::min<qsizetype>(50, i));
        }
    }
    if (const qsizetype at = lowerName.indexOf(query); at >= 0)
        return 700 - int(std::min<qsizetype>(60, at));
    // A run of characters in the app id outranks scattered ones in the name:
    // localised machines depend on it, where "notep" or "calc" appears only
    // in the id and the name is "Notatnik" or "Kalkulator".
    if (const qsizetype at = lowerAppId.indexOf(query); at >= 0)
        return 640 - int(std::min<qsizetype>(60, at));
    if (const int penalty = subsequencePenalty(lowerName, query); penalty >= 0)
        return 560 - std::min(120, penalty);
    // No subsequence tier on the app id. It duplicated what the name already
    // covers and was where the junk came from: nearly every packaged id ends
    // in "!App", so a query of p's and a's matched half the Store.
    return -1;
}

} // namespace

AppsApi::AppsApi(QObject *parent)
    : QObject(parent)
{
    // Defensive, as in AudioApi: QApplication has already put this thread in
    // an STA. S_FALSE means we took a refcount the destructor must give back;
    // RPC_E_CHANGED_MODE means a different model is set but the apartment is
    // still usable and we hold nothing.
    const HRESULT coHr = CoInitializeEx(nullptr, COINIT_APARTMENTTHREADED);
    m_comOwnedByUs = (coHr == S_OK || coHr == S_FALSE);
    if (FAILED(coHr) && coHr != RPC_E_CHANGED_MODE) {
        // Not fatal on its own: the scan reports its own failure and leaves
        // available false, which is what the plugin reacts to.
        qWarning().noquote() << "Apps: CoInitializeEx failed, the app list will be empty";
    }

    // Deliberately NOT under the plugins directory: the manager watches that
    // tree, so a file rewritten on every launch would hot-reload the plugin
    // out from under the user each time they used it.
    m_usagePath = QStandardPaths::writableLocation(QStandardPaths::AppDataLocation)
                  + QStringLiteral("/apps-usage.json");
    loadUsage();

    // One icon per tick, slow enough to stay out of the way of anything the
    // user is actually looking at. See the comment where it is started.
    m_iconWarmTimer.setInterval(25);
    connect(&m_iconWarmTimer, &QTimer::timeout, this, &AppsApi::warmNextIcon);

    // No scan here. Enumerating costs a few hundred ms and the plugin may not
    // even be enabled; the first refresh() from QML pays for it instead.
}

AppsApi::~AppsApi()
{
    if (m_comOwnedByUs)
        CoUninitialize();
}

void AppsApi::setIncludeDesktop(bool on)
{
    if (m_includeDesktop == on)
        return;
    m_includeDesktop = on;
    if (m_sinceScan.isValid())
        refresh(true);
}

void AppsApi::refresh(bool force)
{
    if (!force && m_sinceScan.isValid() && m_sinceScan.elapsed() < kRescanWindowMs)
        return;
    scan();
}

void AppsApi::scan()
{
    QElapsedTimer took;
    took.start();

    m_entries.clear();
    m_available = false;

    // Lowercased display names already taken, so a desktop shortcut to an
    // app the Start list already carries does not show up twice.
    QHash<QString, int> seenNames;
    scanAppsFolder(seenNames);
    const int fromShell = int(m_entries.size());
    if (m_includeDesktop)
        scanDesktop(seenNames);

    // Timed because this is the one call long enough to be felt, and split
    // because "my desktop shortcut is missing" is answered by the second
    // number: shortcuts naming an app the shell already lists are dropped.
    qInfo().noquote() << "Apps: scanned" << fromShell << "entries +"
                      << int(m_entries.size()) - fromShell << "desktop in"
                      << took.elapsed() << "ms";

    m_sinceScan.restart();
    emit changed();

    // Resolving an icon measures ~12 ms, so the eight rows of a fresh query
    // would cost about 100 ms of dead keyboard - and again on the next
    // keystroke. Warming the whole list one icon per tick instead keeps every
    // keystroke free, at the price of a couple of idle seconds after a scan
    // that the user is not waiting on. iconFor() caches, so this only ever
    // pays once per entry.
    m_warmIndex = 0;
    m_iconWarmTimer.start();
}

void AppsApi::warmNextIcon()
{
    if (m_warmIndex >= m_entries.size()) {
        m_iconWarmTimer.stop();
        return;
    }
    iconFor(m_entries.at(m_warmIndex++).id);
}

void AppsApi::scanAppsFolder(QHash<QString, int> &seenNames)
{
    IShellItem *folder = nullptr;
    HRESULT hr = SHCreateItemFromParsingName(L"shell:AppsFolder", nullptr,
                                             IID_PPV_ARGS(&folder));
    if (FAILED(hr) || !folder) {
        qWarning().noquote() << "Apps: cannot open shell:AppsFolder, Apps.available = false";
        return;
    }

    IEnumShellItems *items = nullptr;
    hr = folder->BindToHandler(nullptr, BHID_EnumItems, IID_PPV_ARGS(&items));
    folder->Release();
    if (FAILED(hr) || !items) {
        qWarning().noquote() << "Apps: cannot enumerate shell:AppsFolder, Apps.available = false";
        return;
    }

    IShellItem *item = nullptr;
    while (items->Next(1, &item, nullptr) == S_OK) {
        LPWSTR display = nullptr;
        LPWSTR parsing = nullptr;
        // PARENTRELATIVEPARSING is the app id. Two shapes turn up:
        // "<PackageFamilyName>!App" for a packaged app, and for a Win32 one
        // either a bare "chrome.exe" or a known-folder-relative path ending
        // in the exe. Prefixed it parses back in every case (verified across
        // the whole list), so the whole string is the id and only its last
        // segment is worth showing or matching.
        if (SUCCEEDED(item->GetDisplayName(SIGDN_NORMALDISPLAY, &display))
            && SUCCEEDED(item->GetDisplayName(SIGDN_PARENTRELATIVEPARSING, &parsing))) {
            const QString name = QString::fromWCharArray(display);
            const QString appId = QString::fromWCharArray(parsing);
            if (!name.isEmpty() && !appId.isEmpty()) {
                const QString leaf = appId.section(QLatin1Char('\\'), -1);
                Entry entry;
                entry.name = name;
                entry.id = kAppsFolderPrefix + appId;
                entry.subtitle = prettyAppId(leaf);
                entry.kind = leaf.contains(QLatin1Char('!')) ? QStringLiteral("store")
                                                             : QStringLiteral("app");
                entry.lowerName = name.toLower();
                // The shortened form, same as the subtitle: the package
                // family hash and the "!App" entry point are shared by nearly
                // every packaged app, so matching them invents hits rather
                // than finding any. Empty for a synthesised id, likewise.
                entry.lowerAppId = entry.subtitle.toLower();
                entry.initials = initialsOf(name);
                seenNames.insert(entry.lowerName, 1);
                m_entries.append(entry);
            }
        }
        CoTaskMemFree(display);
        CoTaskMemFree(parsing);
        item->Release();
        item = nullptr;
    }
    items->Release();
    m_available = true;
}

void AppsApi::scanDesktop(QHash<QString, int> &seenNames)
{
    QStringList dirs{ QStandardPaths::writableLocation(QStandardPaths::DesktopLocation) };
    const QString publicDir = qEnvironmentVariable("PUBLIC");
    if (!publicDir.isEmpty())
        dirs << publicDir + QStringLiteral("/Desktop");

    for (const QString &path : std::as_const(dirs)) {
        QDir dir(path);
        if (path.isEmpty() || !dir.exists())
            continue;
        const QFileInfoList files =
            dir.entryInfoList({ QStringLiteral("*.lnk"), QStringLiteral("*.url") }, QDir::Files);
        for (const QFileInfo &file : files) {
            Entry entry;
            entry.name = file.completeBaseName();
            entry.lowerName = entry.name.toLower();
            if (entry.name.isEmpty() || seenNames.contains(entry.lowerName))
                continue;
            // A plain path parses into a PIDL too, so these launch and draw
            // their icon through the same calls as an AppsFolder entry.
            entry.id = QDir::toNativeSeparators(file.absoluteFilePath());
            entry.subtitle = QStringLiteral("Desktop");
            entry.lowerAppId = QStringLiteral("desktop");
            entry.kind = QStringLiteral("shortcut");
            entry.initials = initialsOf(entry.name);
            seenNames.insert(entry.lowerName, 1);
            m_entries.append(entry);
        }
    }
}

int AppsApi::frecencyBonus(const QString &id) const
{
    const auto it = m_usage.constFind(id);
    if (it == m_usage.constEnd() || it->count <= 0)
        return 0;

    // Logarithmic on purpose: the difference between the 1st and 5th launch
    // should matter, between the 40th and 50th should not.
    const double base = std::min(160.0, 40.0 * std::log2(1.0 + it->count));
    const double days = double(QDateTime::currentMSecsSinceEpoch() - it->lastUsedMs)
                        / (24.0 * 60.0 * 60.0 * 1000.0);
    double recency = 0.15;
    if (days < 1.0)
        recency = 1.0;
    else if (days < 7.0)
        recency = 0.7;
    else if (days < 30.0)
        recency = 0.4;
    return int(base * recency);
}

QVariantList AppsApi::search(const QString &query, int limit) const
{
    const QString needle = query.trimmed().toLower();
    QList<std::pair<int, int>> ranked; // score, index into m_entries
    ranked.reserve(m_entries.size());

    for (int i = 0; i < m_entries.size(); ++i) {
        const Entry &entry = m_entries.at(i);
        int score = 0;
        if (needle.isEmpty()) {
            // Nothing typed yet: the launch history is the whole ranking, so
            // an app never launched has nothing to say and stays out.
            score = frecencyBonus(entry.id);
            if (score <= 0)
                continue;
        } else {
            score = matchScore(needle, entry.lowerName, entry.initials, entry.lowerAppId);
            if (score < 0)
                continue;
            score += frecencyBonus(entry.id);
        }
        ranked.append({ score, i });
    }

    // Name breaks ties, so the order of equally good matches does not shift
    // between scans.
    std::sort(ranked.begin(), ranked.end(), [this](const auto &a, const auto &b) {
        if (a.first != b.first)
            return a.first > b.first;
        return m_entries.at(a.second).lowerName < m_entries.at(b.second).lowerName;
    });

    QVariantList out;
    const int wanted = limit > 0 ? std::min(limit, int(ranked.size())) : int(ranked.size());
    out.reserve(wanted);
    for (int i = 0; i < wanted; ++i) {
        const Entry &entry = m_entries.at(ranked.at(i).second);
        out.append(QVariantMap{
            { QStringLiteral("id"), entry.id },
            { QStringLiteral("name"), entry.name },
            { QStringLiteral("subtitle"), entry.subtitle },
            { QStringLiteral("kind"), entry.kind },
        });
    }
    return out;
}

bool AppsApi::launch(const QString &id)
{
    if (id.isEmpty())
        return false;

    const std::wstring parsing = id.toStdWString();
    PIDLIST_ABSOLUTE pidl = nullptr;
    if (FAILED(SHParseDisplayName(parsing.c_str(), nullptr, &pidl, 0, nullptr)) || !pidl) {
        qWarning().noquote() << "Apps: cannot resolve" << id
                             << "- uninstalled since the last scan?";
        return false;
    }

    // SEE_MASK_INVOKEIDLIST runs the item's default verb through its context
    // menu, which is the one call that starts a packaged app, a Win32
    // program and a .lnk without knowing which it is holding.
    SHELLEXECUTEINFOW info = {};
    info.cbSize = sizeof(info);
    info.fMask = SEE_MASK_INVOKEIDLIST | SEE_MASK_FLAG_NO_UI;
    info.lpIDList = pidl;
    info.nShow = SW_SHOWNORMAL;
    const bool started = ShellExecuteExW(&info);
    CoTaskMemFree(pidl);

    if (!started) {
        qWarning().noquote() << "Apps: ShellExecuteEx failed for" << id;
        return false;
    }

    Usage &usage = m_usage[id];
    usage.count += 1;
    usage.lastUsedMs = QDateTime::currentMSecsSinceEpoch();
    saveUsage();
    return true;
}

bool AppsApi::runCommand(const QString &command)
{
    const QString trimmed = command.trimmed();
    if (trimmed.isEmpty())
        return false;

    // Split target from arguments the way the Run box does, honouring one
    // leading quoted path.
    QString target = trimmed;
    QString arguments;
    if (trimmed.startsWith(QLatin1Char('"'))) {
        const qsizetype end = trimmed.indexOf(QLatin1Char('"'), 1);
        if (end > 0) {
            target = trimmed.mid(1, end - 1);
            arguments = trimmed.mid(end + 1).trimmed();
        }
    } else if (const qsizetype space = trimmed.indexOf(QLatin1Char(' ')); space > 0) {
        target = trimmed.left(space);
        arguments = trimmed.mid(space + 1).trimmed();
    }

    // ShellExecute resolves a bare name against PATH and the App Paths
    // registry key, which is why "wt" or "notepad" needs no directory.
    const std::wstring wideTarget = target.toStdWString();
    const std::wstring wideArguments = arguments.toStdWString();
    const HINSTANCE result = ShellExecuteW(nullptr, L"open", wideTarget.c_str(),
                                           arguments.isEmpty() ? nullptr : wideArguments.c_str(),
                                           nullptr, SW_SHOWNORMAL);
    if (reinterpret_cast<INT_PTR>(result) <= 32) {
        qWarning().noquote() << "Apps: cannot run" << trimmed;
        return false;
    }
    return true;
}

QString AppsApi::iconFor(const QString &id)
{
    if (id.isEmpty())
        return {};
    if (const auto it = m_iconCache.constFind(id); it != m_iconCache.constEnd())
        return it.value();

    QString dataUrl;
    const std::wstring parsing = id.toStdWString();
    IShellItem *item = nullptr;
    if (SUCCEEDED(SHCreateItemFromParsingName(parsing.c_str(), nullptr, IID_PPV_ARGS(&item)))
        && item) {
        IShellItemImageFactory *factory = nullptr;
        if (SUCCEEDED(item->QueryInterface(IID_PPV_ARGS(&factory))) && factory) {
            HBITMAP bitmap = nullptr;
            const SIZE wanted = { kIconPixels, kIconPixels };
            // ICONONLY keeps this on the icon path instead of the thumbnail
            // extractors, which can hit the disk; BIGGERSIZEOK takes the next
            // size up rather than upscaling a smaller one.
            if (SUCCEEDED(factory->GetImage(wanted, SIIGBF_ICONONLY | SIIGBF_BIGGERSIZEOK,
                                            &bitmap))
                && bitmap) {
                QImage image = imageFromHBitmap(bitmap);
                DeleteObject(bitmap);
                if (!image.isNull()) {
                    if (image.width() > kIconMaxPixels || image.height() > kIconMaxPixels) {
                        image = image.scaled(kIconMaxPixels, kIconMaxPixels,
                                             Qt::KeepAspectRatio, Qt::SmoothTransformation);
                    }
                    QByteArray png;
                    QBuffer buffer(&png);
                    buffer.open(QIODevice::WriteOnly);
                    image.save(&buffer, "PNG");
                    dataUrl = QStringLiteral("data:image/png;base64,")
                              + QString::fromLatin1(png.toBase64());
                }
            }
            factory->Release();
        }
        item->Release();
    }

    if (m_iconCache.size() >= kIconCacheCap)
        m_iconCache.clear(); // simplest bound: reset rather than grow forever
    m_iconCache.insert(id, dataUrl);
    return dataUrl;
}

void AppsApi::loadUsage()
{
    QFile file(m_usagePath);
    if (!file.open(QIODevice::ReadOnly))
        return; // no history yet is the normal first run

    const QJsonObject root = QJsonDocument::fromJson(file.readAll()).object();
    for (auto it = root.constBegin(); it != root.constEnd(); ++it) {
        const QJsonObject record = it.value().toObject();
        Usage usage;
        usage.count = record.value(QStringLiteral("count")).toInt();
        // toDouble, not toInt: an epoch in milliseconds overflows 32 bits.
        usage.lastUsedMs = qint64(record.value(QStringLiteral("last")).toDouble());
        if (usage.count > 0)
            m_usage.insert(it.key(), usage);
    }
}

void AppsApi::saveUsage() const
{
    // Bounded by dropping the least recently used, so a machine that has
    // launched thousands of things over years does not carry them all.
    QList<QString> ids = m_usage.keys();
    if (ids.size() > kUsageCap) {
        std::partial_sort(ids.begin(), ids.begin() + kUsageCap, ids.end(),
                          [this](const QString &a, const QString &b) {
                              return m_usage.value(a).lastUsedMs > m_usage.value(b).lastUsedMs;
                          });
        ids.resize(kUsageCap);
    }

    QJsonObject root;
    for (const QString &id : std::as_const(ids)) {
        const Usage usage = m_usage.value(id);
        root.insert(id, QJsonObject{
                            { QStringLiteral("count"), usage.count },
                            { QStringLiteral("last"), double(usage.lastUsedMs) },
                        });
    }

    QDir().mkpath(QFileInfo(m_usagePath).absolutePath());
    QFile file(m_usagePath);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Truncate)) {
        qWarning().noquote() << "Apps: cannot write" << m_usagePath
                             << "- ranking will not persist";
        return;
    }
    file.write(QJsonDocument(root).toJson(QJsonDocument::Compact));
}
